[build]
  # Build command for Next.js
  command = "cd frontend && npm install && npm run build"

  # Base directory
  base = "/"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

  # Next.js specific
  NEXT_TELEMETRY_DISABLED = "1"

# Use Netlify's Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables (these will be set in Netlify dashboard)
# NEXT_PUBLIC_API_URL = "your-backend-api-url"
